# Generated by Django 4.2.6 on 2023-11-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_user_country_user_district_user_name_user_postalcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cardnumber',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cvv',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mm',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='yy',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
