# Generated by Django 4.2.6 on 2023-11-29 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_user_cardnumber_user_cvv_user_mm_user_yy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cardnumber',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mm',
        ),
        migrations.RemoveField(
            model_name='user',
            name='yy',
        ),
    ]
