# Generated by Django 4.2.6 on 2023-12-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_handfree_pendrive_powerbank_maintable'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintable',
            name='photo',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
    ]
