# Generated by Django 4.2.6 on 2023-12-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_maintable_sname'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintable',
            name='cname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Maintabl1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(max_length=200)),
                ('sname', models.CharField(blank=True, max_length=200, null=True)),
                ('photo', models.ImageField(blank=True, max_length=200, null=True, upload_to='')),
                ('handfree', models.ManyToManyField(to='blog.handfree')),
                ('pendrive', models.ManyToManyField(to='blog.pendrive')),
                ('powerbank', models.ManyToManyField(to='blog.powerbank')),
            ],
        ),
    ]
