# Generated by Django 4.2.6 on 2023-12-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_maintable_cname_maintabl1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lasttable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('price', models.CharField(max_length=100)),
                ('count', models.CharField(max_length=20)),
                ('total', models.CharField(max_length=50)),
                ('orderid', models.CharField(max_length=50)),
                ('esdate', models.CharField(max_length=100)),
                ('ordate', models.CharField(max_length=100)),
            ],
        ),
    ]
