# Generated by Django 4.2.6 on 2023-12-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_user_lastorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='lasttable',
            name='photo',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
    ]
