# Generated by Django 4.2.6 on 2023-12-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_remove_lasttable_photo_lasttable_photourl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='lastorder',
        ),
        migrations.AddField(
            model_name='lasttable',
            name='userid',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
