# Generated by Django 4.2.6 on 2023-12-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_remove_user_lastorder_lasttable_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='carttable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('price', models.CharField(max_length=50)),
                ('photo', models.CharField(max_length=500)),
                ('iname', models.CharField(max_length=50)),
                ('iid', models.CharField(max_length=10)),
                ('uid', models.CharField(max_length=10)),
            ],
        ),
    ]
