# Generated by Django 4.2.6 on 2023-12-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_carttable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviewtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=10)),
                ('comments', models.CharField(max_length=1000)),
                ('photo', models.ImageField(blank=True, max_length=200, null=True, upload_to='')),
                ('odate', models.CharField(max_length=10)),
                ('iname', models.CharField(max_length=50)),
                ('iid', models.CharField(max_length=20)),
                ('cfname', models.CharField(max_length=20)),
                ('clname', models.CharField(max_length=20)),
            ],
        ),
    ]
