# Generated by Django 4.2.6 on 2023-12-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_reviewtable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Totaltable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iname', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=500)),
                ('price', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=500)),
            ],
        ),
    ]
