# Generated by Django 4.2.6 on 2023-12-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_alter_totaltable_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lasttable',
            name='itemid',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
