# Generated by Django 4.2.6 on 2023-12-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_lasttable_itemid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewtable',
            name='odate',
            field=models.CharField(max_length=100),
        ),
    ]
