# Generated by Django 4.2.6 on 2023-12-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_alter_reviewtable_odate'),
    ]

    operations = [
        migrations.AddField(
            model_name='totaltable',
            name='avreview',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='totaltable',
            name='recount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
