# Generated by Django 4.2.6 on 2023-12-29 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_remove_maintabl1_handfree_remove_maintabl1_pendrive_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carttable',
            name='iname',
        ),
    ]
